### ISSUE TITLE
[ EMS ] : INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>

### ISSUE THREAD

**Issue by chiriaev** [schubergphilis/vagrant-cloudstack#10]
Guys, Hi. My "vagrant-cloudstack" is "0.0.5" and "Vagrant" is "1.3.4" 

I have the following statement tried 60 times every 2 seconds. 
...
INFO retryable: Retryable exception raised: Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded
...

What happens in the meantime (i.e.: what's sent from my test box to the cloud API):

[a.] An instance is created, I can see that in the Cloud portal. During this phase it is initializing. It takes from 3 to 5 minutes.
…
Request: /client/api?templateid=dafa6819-465d-4e87-bb21-d66f3ca5f1f1&serviceofferingid=a6fdb90b-9d56-4927-a2fe-386f9d473237&zoneid=d73e8d08-f1e6-4e67-9030-ff58f36b7b20&displayname=root_test
_1383140024&projectid=4c730aab-07ca-4a07-af24-ce13b50bc205&command=deployVirtualMachine&networkids=242d4c4c-4f0c-43d4-86f5-03d51ef531a1&response=json&apiKey=[MY_API_KEY]&signature=vM%2BSSI1qtFZHWhmQ%2BlhDTeEc2SI%3D

Response: { "deployvirtualmachineresponse" : {"id":"a65c3302-2fe0-4a86-8424-9aa2e2bd76f0","jobid":"b8097319-297a-44bc-afdf-01f002f2399f"} }

[b.] When point “[a.]” is completed the “cloudstack” will try every 2 seconds and for 60 tries request the following:
…
Request:  /client/api?id=a65c3302-2fe0-4a86-8424-9aa2e2bd76f0&command=listVirtualMachines&response=json&apiKey=[MY_API_KEY]&signature=nJip8J2r9MhXD9ZyRkc4Dm8L0EQ%3D

Response: { "listvirtualmachinesresponse" : { } }

After 60 tries, Vagrant throws en exception when it tries to destroy the VM. Which makes sense looking at the above. This being said the VM itself is still not flagged as running in the Portal, at that point in time.

My problem is that even when it’s running, firing the “[b.]” URL again wont’ change the returned body.  (i.e.: will remain “{ "listvirtualmachinesresponse" : { } }”)

Wondering what’s wrong.

Thanks in advance.

**Comment by chiriaev** [comment]
Ok, I think I know. When tried a Python based wrapper to list my VM(s), had to add the "projectid" attribute to make it work. For some reasons, this attribute is not appended to the "/client/api?id=a65c3302-2fe0-4a86-8424-9aa2e2bd76f0&command=listVirtualMachines&response=json&apiKey=[MY_API_KEY]&signature=nJip8J2r9MhXD9ZyRkc4Dm8L0EQ%3D" when you are doing your iterations: 
...
Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded
..

The "cloudstack.project_id=" is defined in my Vagrant configuration; and works as it's passed in the first call.

Thanks for getting back.

**Comment by loa** [comment]
Yea we have noticed this issue.

Basically is that all commands like stop, start, destroy etc work by only providing the id for the virtual machine. But the listvirtualmachines require the projectid to be able to find the vm even if you provide the id. 

If you provide the projectid=-1 it will find your machine in projects but not in the default view.

Here we basically use the vagrant-cloudstack only towards the default project but we want it to work with projects as well.

**Comment by chiriaev** [comment]
Thanks for that, Loa. … in the meantime, I hardcoded the assignment in Fog. Any time-frame for an out-of-the-box support? 

Regards, Andrei

**Comment by chiriaev** [comment]
Loa, Hi. Any luck? I haven't noticed any updates in the latest commit. Regards, Andrei

**Comment by loa** [comment]
We have not done anything regarding this so far.

The complicated thing is that the api calls to Cloudstack is done in the Fog gem. So the change should be inside of Fog to be able to do this _(that is find the machine with uuid independently of what project it resides in)_.

**Comment by chiriaev** [comment]
Loa, Hi. I hope you are well. I posted a query to the Fog's folks, aAs per the below. Could you please perhaps suggest an implementation variant, from your point of view, "vagran-cloudstack"? Or at least encourage them? 
…
https://github.com/fog/fog/issues/2695
…

Thanks in advance and Regards, Andrei

**Comment by loa** [comment]
This is getting on our nerves as well. I will look into this tomorrow and get back to you.

**Comment by loa** [comment]
We have decided to hack together a fix for fog, send a pull-request and start a conversation for the real fix with the fog maintainers. 

Hopefully I will get time for this tomorrow.

**Comment by chiriaev** [comment]
Brilliant! Thanks. Regards, Andrei

**Comment by loa** [comment]
Proposed a fix with explanation at fog/fog#2713

Hope we can get a fix for this soon.

**Comment by chiriaev** [comment]
Great! Thanks a lot, Loa!!! Regards, Andrei

**Comment by mindjiver** [comment]
@ems-dev The latest version 0.5.0 which I will release today should contain a fix for this.

**Comment by chiriaev** [comment]
Marvelous! Thanks. Regards, Andrei

**Comment by mindjiver** [comment]
It should be released on rubygems.org now, please verify that it works so we can close this issue @ems-dev . https://rubygems.org/gems/vagrant-cloudstack

**Comment by mindjiver** [comment]
bump, @ems-dev have you had time to verify this?

**Comment by chiriaev** [comment]
Yes. Thanks! Regards, Andrei

**Comment by mindjiver** [comment]
Thanks! Please try the new version if you have time as well! It's awesome!
