### ISSUE TITLE
Issue with missing host parameter

### ISSUE THREAD

**Issue by wingZero21** [schubergphilis/vagrant-cloudstack#12]
Hi,

When trying to vagrant up on the cloudstack option it brings back the below error.

Bringing machine 'default' up with 'cloudstack' provider...
C:/Users/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/core/service.rb:208:in `validate_options': Missing required arguments: cloudstack_host (ArgumentError)
        from C:/Users/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/core/service.rb:58:in`new'
        from C:/Users/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/compute.rb:44:in `new'
        from C:/Users/.vagrant.d/gems/gems/vagrant-cloudstack-0.0.6/lib/vagrant-cloudstack/action/connect_cloudstack.rb:40:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in`busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in`action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'

Using the below parameters
  config.vm.provider :cloudstack do |cloudstack, override|
    cloudstack.host = "cloudstackhost"
    cloudstack.path = "/client/api"
    cloudstack.port = "8080"
    cloudstack.scheme = "http"
    cloudstack.api_key = ""
    cloudstack.secret_key = ""

```
cloudstack.template_id = ""
cloudstack.service_offering_id = ""
cloudstack.network_id = ""
cloudstack.zone_id = ""
cloudstack.project_id = "test"
```

  end
end

**Comment by wingZero21** [comment]
Ok to fix this I removed the below

Vagrant.configure("2") do |config|

and the last end on the front page example and its got a bit further.

**Comment by loa** [comment]
You still having issues or you resolved it?

**Comment by wingZero21** [comment]
Yeah I fixed that particular problem by removing Vagrant.configure("2") do |config| from the conf cheers
