### ISSUE TITLE
Any chance setting VM hostname will be implemented

### ISSUE THREAD

**Issue by sarral** [schubergphilis/vagrant-cloudstack#36]
My PROVIDER sets VM hostname to the VM-ID. Vagrant/cloud-stack doesn't support setting network vals.  The API call to createVirtualMachine() has hostname parameter.

Setting hostname on VM doesn't update PROVIDER and internal DNS. ( I can't nslookup my machine based on set hostname, but on hostname in UI, auto-generated).

I can set with Puppet, but again doesn't update PROVIDER DNS.

Please ;)

**Comment by sarral** [comment]
correction. API call: deployVirtualMachine() the 'name' parameter sets hostname

**Comment by mindjiver** [comment]
@sarral I think it should be possible. We can take a look.

**Comment by sarral** [comment]
Thanks !!!

**Comment by nrocco** [comment]
Having this feature would truly complete my awesome vagrant cloudstack setup. +1

**Comment by mindjiver** [comment]
@nrocco we just recently upgraded our CloudStack setup to support this. Now we have possibility to test this. It's on our backlog :smile: 

// =^.^=

**Comment by nrocco** [comment]
@mindjiver we are happy to help with testing on our cloudstack platform as well, if that helps.

You by any change can provide us with code?

**Comment by mindjiver** [comment]
@nrocco We will release 0.9.0 today, please test that one out :smile_cat:

**Comment by lndbrg** [comment]
@nrocco 0.9.0 has been released. Please try it out.

**Comment by nrocco** [comment]
Great news! I'll try it out. 

## 

Nico Di Rocco
