### ISSUE TITLE
Provide possibility to specify template names

### ISSUE THREAD

**Issue by sergeyevstifeev** [schubergphilis/vagrant-cloudstack#39]
Currently the templates are specified using template UUIDs. It would be great to be able to provide template names as an alternative. Template names are nicer from readability and maintenance (no need to update configs if the template is updated and put under the same name) standpoints.

**Comment by lndbrg** [comment]
Yes, we need to figure out if we want to upstream this funtionality to the cloud library fog or if we want to implement it just for vagrant-cloudstack.

It's preferable to do it in fog, but that might take longer time.

**Comment by lndbrg** [comment]
This is being implemented in #47

**Comment by lndbrg** [comment]
FIXED!
