### ISSUE TITLE
Support the 'reload' command

### ISSUE THREAD

**Issue by sergeyevstifeev** [schubergphilis/vagrant-cloudstack#40]
It would be nice to support the 'reload' command (https://docs.vagrantup.com/v2/cli/reload.html).

**Comment by lndbrg** [comment]
What version are you using? This should be implemented since about 6 months ago: https://github.com/klarna/vagrant-cloudstack/commit/4dcfeea9790a84058736c962929681b419af44fc

**Comment by sergeyevstifeev** [comment]
@lndbrg ahh, indeed, it was the version we have in chefkitchen, which is stoneage (0.0.3). Works in the latest version.
