### ISSUE TITLE
QUESTION: What is this file for? 

### ISSUE THREAD

**Issue by sarral** [schubergphilis/vagrant-cloudstack#44]
.vagrant/machines/default/cloudstack/index_uuid

index_uuid: What is that a UUID for?

Thanks.

**Comment by loa** [comment]
It's built into vagrant itself.

Vagrant keep track of the VMs it create this way, if you try vagrant with Virtualbox you will have the same file but called .vagrant/machines/default/virtualbox/index_uuid instead (or something equivalent).

Hope this answers your question :)
