### ISSUE TITLE
Does this support PublicCloud services?

### ISSUE THREAD

**Issue by snumano** [schubergphilis/vagrant-cloudstack#6]
Hi,
I'm trying this plugin to use Contegix CloudService(CloudStack3.0), but vagrant up fails.I'm checking the result now.
Please let me know  folowings,

1.The endpoint of Contegix is as below.
  Does this plugin support the API ptah "portal/client/api" ?
  https://cloud.contegix.com/portal/client/api

2.Does this plugin support both CloudStack 3.0.x and 2.2.x ?

3.What environment have you tested?
  Private Cloud? Public Cloud? Both?

Thanks,

**Comment by loa** [comment]
1. Should work by including the /portal to the cloudstack path:
   
     config.vm.provider :cloudstack do |cloudstack, override|
     cloudstack.host = "cloudstack.local"
     cloudstack.path = "portal/client/api"
     cloudstack.port = "8080"
2. We are running Cloudstack 3.0.x. Can't answer for 2.2.x.
3. Private internal cloud.
